### ISSUE TITLE
Help is not displayed on case sensitive OS

### ISSUE THREAD

**Issue by ewidance** [scargill/scheduler#1]
To fix : `script type="text/x-red" data-help-name="Scheduler">` becomes `<script type="text/x-red" data-help-name="scheduler">` in node-red-node-scheduler/scheduler.html

**Comment by scargill** [comment]
Not using github any more - using bitbucket/scargill....

**Comment by ewidance** [comment]
1/ Who know you don't use it anymore?  You should edit readme and add a note that project has moved....
2/ Same bug on you Bitcucklet sources.
3/ Thanks dear user for signaling me a bug, helping me to improve my code. :)
